server:
  port: 10010
spring:
  application:
    name: yx-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10   # 服务拉取间隔时间为10秒
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api       # 路由前缀
  retryable: true   # 开启重试机制
  routes:
    item-service: /item/**  # 商品微服务
    search-service: /search/** # 搜索微服务
    user-service: /user/**  # 用户微服务
    auth-service: /auth/**  # 授权中心微服务
    cart-service: /cart/**
  ignored-services:
    - upload-service # 忽略upload-server服务
  add-host-header: true # 携带请求本身的head头信息
  sensitive-headers:  # 覆盖敏感头信息，使cookie可以正常写入
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
youxiang:
  jwt:
    pubKeyPath: C:\\java\\rsa\\rsa.pub # 公钥地址
    cookieName: YX_TOKEN
  filter:
    allowPaths:   # 配置白名单
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item