server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB  # 限制文件上传的大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #10秒不发送就过期
    lease-renewal-interval-in-seconds: 5  #每隔3秒发送一次心跳
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image:
    width: 60
    height: 60
  tracker-list: # tracker地址：虚拟机服务器地址+端口(默认端口22122)
    - 192.168.182.100:22122