server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/youxiang?serverTimezone=UTC
    username: root
    password: '0826'
  rabbitmq:                # 配置rabbitmq
    host: 192.168.182.100  # 默认使用5672端口
    username: youxiang
    password: youxiang
    virtual-host: /youxiang
    template:
      exchange: YOUXIANG.ITEM.EXCHANGE # 设置默认路由
    publisher-confirm-type: correlated # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15    # 15秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}